config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, except: [:new, :create]
    resources :deleted_users, only: [:index, :show]

    root to: 'users#index'
  end

  resource :user do
    get :delete, on: :member
  end
  get 'create', to: 'users#new'

  resources :sessions, only: :create
  get '/destroy_session', to: 'sessions#destroy', as: :destroy_session

  get '/confirm/:key', to: 'email_confirmations#confirm', as: :confirm_email
  get '/resend_confirmation', to: 'email_confirmations#resend', as: :resend_confirmation

  resources :forgot_passwords, only: [:new, :create, :edit, :update]

  # this is just a convenience to create a named route to rack-cas' logout
  get '/logout' => -> env { [404, { 'Content-Type' => 'text/html' }, ['Rack::CAS should have caught this']] }, as: :cas_logout

  root to: 'users#new'
end

app/models/forgot_password.rb
class ForgotPassword
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :non_biolan
  field :key, type: String
  field :expires_at, type: Time
  field :used, type: Boolean

  scope :active, -> { where(:used.ne => true, :expires_at.gte => Time.now) }

  validates :non_biolan_id, :key, :expires_at, presence: true

  before_validation :set_key, :set_expires_at

  private

  def set_key
    self.key ||= SecureRandom.hex
  end

  def set_expires_at
    self.expires_at = Time.now + Settings.password.reset_expire
  end
end

app/controllers/forgot_passwords_controller.rb
class ForgotPasswordsController < ApplicationController
  include Session

  def new
    authorize nil
  end

  def create
    authorize nil

    if user = NonBiolan.where(email: params[:email]).first
      forgot_password = ForgotPassword.create! non_biolan: user

      UserMailer.password_reset(forgot_password).deliver_now

      redirect_to root_url, notice: 'Your password reset link has been sent. Please check your inbox.'
    else
      redirect_to new_forgot_password_path, alert: 'No user account with that email was found'
    end
  end

  def edit
    @forgot_password = ForgotPassword.active.find_by(key: params[:id])

    authorize @forgot_password
  end

  def update
    @forgot_password = ForgotPassword.active.find_by(key: params[:id])
    @user = @forgot_password.non_biolan

    authorize @forgot_password

    if @user.update user_params
      login! @user
      @forgot_password.update! used: true
      redirect_to edit_user_path, notice: 'Your password has been changed'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:non_biolan).permit :password, :password_confirmation
  end

  def policy(_)
    ForgotPasswordPolicy.new(current_user, nil)
  end
end

app/views/forgot_passwords/edit.html.slim
.page-segment
  .container
    .row
      .col-xs-12
        h2 Reset Forgotten Password
        p Enter a new password below to update your forgotten password.

    .row
      .col-xs-6
        = form_for @forgot_password.non_biolan, url: forgot_password_path(@forgot_password.key) do |f|
          .form-group
            = f.label :password do
              ' New Password
              small.text-muted twice
            .row
              .col-sm-6
                = f.password_field :password, class: 'form-control'
              .col-sm-6
                = f.password_field :password_confirmation, class: 'form-control'
            .progress style="margin-top: 10px;"
              .progress-bar role="progressbar" style="width: 0%;"
                | very weak
          = f.submit 'Change Password', class: 'btn btn-primary'

app/views/forgot_passwords/new.html.slim
.page-segment
  .container
    .row
      .col-xs-12
        h2 Forgot Password
        p If you've forgotten your password, simply enter the email address associated with your account below and a password reset link will be sent to you.

    .row
      .col-xs-4
        = form_tag forgot_passwords_path, method: :post do
          .form-group
            = label_tag :email
            = text_field_tag :email, nil, class: 'form-control', tabindex: 1
          = submit_tag 'Reset Password', class: 'btn btn-primary', tabindex: 2