config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, except: [:new, :create]
    resources :deleted_users, only: [:index, :show]

    root to: 'users#index'
  end

  resource :user do
    get :delete, on: :member
  end
  get 'create', to: 'users#new'

  resources :sessions, only: :create
  get '/destroy_session', to: 'sessions#destroy', as: :destroy_session

  get '/confirm/:key', to: 'email_confirmations#confirm', as: :confirm_email
  get '/resend_confirmation', to: 'email_confirmations#resend', as: :resend_confirmation

  resources :forgot_passwords, only: [:new, :create, :edit, :update]

  # this is just a convenience to create a named route to rack-cas' logout
  get '/logout' => -> env { [404, { 'Content-Type' => 'text/html' }, ['Rack::CAS should have caught this']] }, as: :cas_logout

  root to: 'users#new'
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # We don't need a complicated email matcher since we confirm the email on the
  # account anyway but it's good to make sure up front that people don't try to
  # use a simple username that's not an email.
  VALID_EMAIL_MATCHER = /
    \A # beginning of string
    .+ # any one or more characters
    @  # a literal "@"
    .+ # any one or more characters
    \. # a literal period
    .+ # any one or more characters
    \Z # end of string
  /x

  field :uuid, type: String
  field :username, type: String
  field :email, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :user_agent, type: String # from when the account was created
  field :ip_address, type: String # from when the account was created

  validates :email, :first_name, :last_name, presence: true
  validates :email, uniqueness: true, format: {with: VALID_EMAIL_MATCHER}

  before_save :set_uuid, :set_username

  def name
    [first_name, last_name].reject(&:blank?).join (' ')
  end

  def new?
    created_at.to_i > (Time.now - Settings.users.new_before).to_i
  end

  private

  def set_uuid
    self.uuid ||= SecureRandom.uuid
  end

  def set_username
    self.username ||= email
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    users = policy_scope(User).all

    if params[:q]
      begin
        regex = Regexp.new(params[:q].gsub(/\s/, '.*'), Regexp::IGNORECASE)
        ids = User.collection.aggregate([
          {:$project =>
            {
              uuid: '$uuid',
              email: '$email',
              full_name: {:$concat => ['$first_name', ' ', '$last_name']}
            }
          },
          {:$match => {:$or => [
            {uuid: regex},
            {email: regex},
            {full_name: regex}
          ]}}
        ]).map { |p| p[:_id] }

        users = policy_scope(User).where(:id.in => ids)
      rescue RegexpError
        users = User.none
      end
    end

    @users = users.asc(:last_name, :first_name).page(params[:page])
  end

  def show
    @user = NonBiolan.find(params[:id])

    authorize @user

    if @user.unconfirmed?
      flash.now.notice = "This user has not yet confirmed their email"
    end
  end

  def edit
    @user = NonBiolan.find(params[:id])

    authorize @user
  end

  def update
    @user = NonBiolan.find(params[:id])

    authorize @user

    user_prms = user_params
    if params[:trogdir_id].present?
      uuid = TrogdirPerson.new(params[:trogdir_id], params[:trogdir_id_type]).uuid
      user_prms.merge! trogdir_uuid: uuid if uuid.present?
    end

    if @user.update user_prms
      redirect_to admin_user_path(@user), notice: 'User updated'
    else
      render :edit
    end
  end

  def destroy
    @user = NonBiolan.find(params[:id])

    authorize @user

    deleted_user = @user.backup_and_destroy!

    redirect_to admin_deleted_user_path(deleted_user), notice: 'User deleted'
  end

  protected

  def search_path
    admin_users_path
  end

  private

  def user_params
    params.require(:non_biolan).permit :first_name, :last_name, :username, :email, :password, :password_confirmation, :confirmed_at, :trogdir_uuid
  end

  def policy(user)
    Admin::UserPolicy.new(current_user, user)
  end

  def pundit_policy_scope(scope)
    Admin::UserPolicy::Scope.new(current_user, scope).resolve
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Session

  def show
    load_user

    authorize @user

    if @user.confirmed?
      redirect_to edit_user_path
    end
  end

  def new
    @user = NonBiolan.new

    authorize @user

    if current_user.present?
      redirect_to user_path
    else
      session[:referring_url] ||= request.referrer
      session[:return_url] = params[:return] if params[:return].present?

      store_and_render_view create_path? ? :new : :login_or_new
    end
  end

  def create
    @user = NonBiolan.new(user_params)
    @user.user_agent = request.user_agent
    @user.ip_address = request.ip

    authorize @user

    if @user.save
      UserMailer.email_confirmation(@user).deliver_now
      login! @user
      redirect_to user_path
    else
      store_and_render_view flash[:view] || :login_or_new
    end
  end

  def edit
    load_user
    authorize @user
  end

  def update
    load_user

    authorize @user

    if user_params[:password].present? && !@user.authenticate(params[:current_password])
      flash.now.alert = 'Invalid current password'
      flash.now[:show_password_dialog] = true
      render :edit
    elsif @user.update user_params
      redirect_to edit_user_path, notice: 'Changes saved'
    else
      if user_params[:password].present?
        flash.now[:show_password_dialog] = true
      end

      render :edit
    end
  end

  def delete
    load_user

    authorize @user
  end

  def destroy
    load_user

    authorize @user

    @user.backup_and_destroy!
    logout!
    redirect_to root_url, notice: 'Account deleted'
  end

  private

  def load_user
    @user ||= current_user
  end

  def create_path?
    request.path =~ /\A\/create/
  end

  def store_and_render_view(view)
    flash[:view] = view
    render view
  end

  def user_params
    params.require(:non_biolan).permit :first_name, :last_name, :email, :password, :password_confirmation, :referring_url
  end

  def policy(user)
    UserPolicy.new(current_user, user)
  end
end

app/views/users/_change_password_dialog.html.slim
- if flash[:show_password_dialog]
  - content_for :javascript do
    coffee:
      $('#change_password_modal').modal 'show'

#change_password_modal.modal.fade role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      = form_for @user, url: user_path do |f|
        .modal-header
          button.close type="button" data-dismiss="modal" &times;
          h4 Change Password
        .modal-body
          .form-group
            = label_tag :current_password
            = password_field_tag :current_password, nil, class: 'form-control'
          .form-group
            = f.label :password do
              ' New Password
              small.text-muted twice
            .row
              .col-sm-6
                = f.password_field :password, class: 'form-control'
              .col-sm-6
                = f.password_field :password_confirmation, class: 'form-control'
            .progress style="margin-top: 10px;"
              .progress-bar role="progressbar" style="width: 0%;"
                | very weak
        .modal-footer
          button.btn.btn-default type="button" data-dismiss="modal" Cancel
          = f.submit 'Change Password', class: 'btn btn-primary'

app/views/users/_new_form.html.slim
h2 Create Account
= form_for @user, url: user_path do |f|
  = f.hidden_field :referring_url, value: session[:referring_url]
  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: 'form-control', tabindex: 5
  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control', tabindex: 6
  .form-group
    = f.label :email
    = f.email_field :email, class: 'form-control', tabindex: 7
  .form-group
    = f.label :password do
      ' Password
      small.text-muted twice
    .row
      .col-sm-6
        = f.password_field :password, class: 'form-control', tabindex: 8
      .col-sm-6
        = f.password_field :password_confirmation, class: 'form-control', tabindex: 9

    .progress style="margin-top: 10px;"
      .progress-bar role="progressbar" style="width: 0%;"
        | very weak

  = f.submit 'Create Account', class: 'btn btn-primary', tabindex: 10

app/views/users/delete.html.slim
.page-segment
  .container
    .row
      .col-md-12
        h2 Delete Your Account?

        p
          strong Are you sure you want to delete your account?
          br
          | Your will no longer be able to login to any Biola sites with this account.

        = form_tag user_path, method: :delete do
          => link_to 'Back', edit_user_path, class: 'btn btn-default', tabindex: 1
          = submit_tag 'Delete Account', class: 'btn btn-danger', tabindex: 2

app/views/users/edit.html.slim
= render 'change_password_dialog'

.page-segment
  .container
    .row
      .col-md-12
        h2 Edit Account Info
    .row
      .col-md-6
        = form_for @user, url: user_path do |f|
          .form-group
            = f.label :username
            = f.text_field :username, class: 'form-control', disabled: true
          .form-group
            = f.label :first_name
            = f.text_field :first_name, class: 'form-control', tabindex: 1
          .form-group
            = f.label :last_name
            = f.text_field :last_name, class: 'form-control', tabindex: 2
          .form-group
            = f.label :email, 'Contact Email'
            #email_warning.alert.alert-warning style="display: none;"
              i.fa.fa-warning>
              | You can change your email address but your old email address in the username field above will continue to be the username you must use to login.
            = f.email_field :email, class: 'form-control', data: {warning: '#email_warning'}, tabindex: 3
          = f.submit 'Update Account', class: 'btn btn-primary', tabindex: 4

      .col-md-6
        h3 Change Password
        = link_to 'Change Password', '#', class: 'btn btn-default', data:{toggle: 'modal', target: '#change_password_modal'}, tabindex: 5

        h3 Delete Account
        = link_to 'Delete Account', delete_user_path, class: 'btn btn-danger', tabindex: 6

app/views/users/login_or_new.html.slim
.page-segment
  .container
    .row
      .col-sm-5
        h2 Login
        = form_tag sessions_path do
          .form-group
            = label_tag :username
            = email_field_tag 'session[username]', flash[:login_username], id: :username, class: 'form-control', tabindex: 1, placeholder: 'bob@example.com'
          .form-group
            = label_tag :password
            = password_field_tag 'session[password]', nil, id: :password, class: 'form-control', tabindex: 2
            = link_to 'Forgot password?', new_forgot_password_path, tabindex: 3
          = submit_tag 'Login', class: 'btn btn-primary', tabindex: 4
      .col-sm-2
        span.or or
      .col-sm-5
        = render 'new_form'

app/views/users/new.html.slim
.page-segment
  .container
    .row
      .col-sm-5
        = render 'new_form'

app/views/users/show.html.slim
.page-segment
  .container
    .row
      h2 Please Confirm Your Email Address

      p An email has been sent to #{mail_to(current_user.email, current_user.email)}. Please check your inbox to complete your registration.

      = link_to 'Resend Confirmation Email', resend_confirmation_path, class: 'btn btn-default btn-sm'