config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, except: [:new, :create]
    resources :deleted_users, only: [:index, :show]

    root to: 'users#index'
  end

  resource :user do
    get :delete, on: :member
  end
  get 'create', to: 'users#new'

  resources :sessions, only: :create
  get '/destroy_session', to: 'sessions#destroy', as: :destroy_session

  get '/confirm/:key', to: 'email_confirmations#confirm', as: :confirm_email
  get '/resend_confirmation', to: 'email_confirmations#resend', as: :resend_confirmation

  resources :forgot_passwords, only: [:new, :create, :edit, :update]

  # this is just a convenience to create a named route to rack-cas' logout
  get '/logout' => -> env { [404, { 'Content-Type' => 'text/html' }, ['Rack::CAS should have caught this']] }, as: :cas_logout

  root to: 'users#new'
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # We don't need a complicated email matcher since we confirm the email on the
  # account anyway but it's good to make sure up front that people don't try to
  # use a simple username that's not an email.
  VALID_EMAIL_MATCHER = /
    \A # beginning of string
    .+ # any one or more characters
    @  # a literal "@"
    .+ # any one or more characters
    \. # a literal period
    .+ # any one or more characters
    \Z # end of string
  /x

  field :uuid, type: String
  field :username, type: String
  field :email, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :user_agent, type: String # from when the account was created
  field :ip_address, type: String # from when the account was created

  validates :email, :first_name, :last_name, presence: true
  validates :email, uniqueness: true, format: {with: VALID_EMAIL_MATCHER}

  before_save :set_uuid, :set_username

  def name
    [first_name, last_name].reject(&:blank?).join (' ')
  end

  def new?
    created_at.to_i > (Time.now - Settings.users.new_before).to_i
  end

  private

  def set_uuid
    self.uuid ||= SecureRandom.uuid
  end

  def set_username
    self.username ||= email
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    users = policy_scope(User).all

    if params[:q]
      begin
        regex = Regexp.new(params[:q].gsub(/\s/, '.*'), Regexp::IGNORECASE)
        ids = User.collection.aggregate([
          {:$project =>
            {
              uuid: '$uuid',
              email: '$email',
              full_name: {:$concat => ['$first_name', ' ', '$last_name']}
            }
          },
          {:$match => {:$or => [
            {uuid: regex},
            {email: regex},
            {full_name: regex}
          ]}}
        ]).map { |p| p[:_id] }

        users = policy_scope(User).where(:id.in => ids)
      rescue RegexpError
        users = User.none
      end
    end

    @users = users.asc(:last_name, :first_name).page(params[:page])
  end

  def show
    @user = NonBiolan.find(params[:id])

    authorize @user

    if @user.unconfirmed?
      flash.now.notice = "This user has not yet confirmed their email"
    end
  end

  def edit
    @user = NonBiolan.find(params[:id])

    authorize @user
  end

  def update
    @user = NonBiolan.find(params[:id])

    authorize @user

    user_prms = user_params
    if params[:trogdir_id].present?
      uuid = TrogdirPerson.new(params[:trogdir_id], params[:trogdir_id_type]).uuid
      user_prms.merge! trogdir_uuid: uuid if uuid.present?
    end

    if @user.update user_prms
      redirect_to admin_user_path(@user), notice: 'User updated'
    else
      render :edit
    end
  end

  def destroy
    @user = NonBiolan.find(params[:id])

    authorize @user

    deleted_user = @user.backup_and_destroy!

    redirect_to admin_deleted_user_path(deleted_user), notice: 'User deleted'
  end

  protected

  def search_path
    admin_users_path
  end

  private

  def user_params
    params.require(:non_biolan).permit :first_name, :last_name, :username, :email, :password, :password_confirmation, :confirmed_at, :trogdir_uuid
  end

  def policy(user)
    Admin::UserPolicy.new(current_user, user)
  end

  def pundit_policy_scope(scope)
    Admin::UserPolicy::Scope.new(current_user, scope).resolve
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Session

  def show
    load_user

    authorize @user

    if @user.confirmed?
      redirect_to edit_user_path
    end
  end

  def new
    @user = NonBiolan.new

    authorize @user

    if current_user.present?
      redirect_to user_path
    else
      session[:referring_url] ||= request.referrer
      session[:return_url] = params[:return] if params[:return].present?

      store_and_render_view create_path? ? :new : :login_or_new
    end
  end

  def create
    @user = NonBiolan.new(user_params)
    @user.user_agent = request.user_agent
    @user.ip_address = request.ip

    authorize @user

    if @user.save
      UserMailer.email_confirmation(@user).deliver_now
      login! @user
      redirect_to user_path
    else
      store_and_render_view flash[:view] || :login_or_new
    end
  end

  def edit
    load_user
    authorize @user
  end

  def update
    load_user

    authorize @user

    if user_params[:password].present? && !@user.authenticate(params[:current_password])
      flash.now.alert = 'Invalid current password'
      flash.now[:show_password_dialog] = true
      render :edit
    elsif @user.update user_params
      redirect_to edit_user_path, notice: 'Changes saved'
    else
      if user_params[:password].present?
        flash.now[:show_password_dialog] = true
      end

      render :edit
    end
  end

  def delete
    load_user

    authorize @user
  end

  def destroy
    load_user

    authorize @user

    @user.backup_and_destroy!
    logout!
    redirect_to root_url, notice: 'Account deleted'
  end

  private

  def load_user
    @user ||= current_user
  end

  def create_path?
    request.path =~ /\A\/create/
  end

  def store_and_render_view(view)
    flash[:view] = view
    render view
  end

  def user_params
    params.require(:non_biolan).permit :first_name, :last_name, :email, :password, :password_confirmation, :referring_url
  end

  def policy(user)
    UserPolicy.new(current_user, user)
  end
end

app/views/admin/users/_trogdir_person.html.slim
- editable ||= false
.panel.panel-default#trogdir_person
  .panel-heading
    - if editable
      button.close type="button" data-dismiss="alert" data-target="#trogdir_person"
        span &times;
    strong = @user.trogdir_person.name
  .panel-body
    .media
      .media-left
        - if trogdir_person.photo_url.present?
          img.id_photo.img-thumbnail.pull-left srctrogdir_person.photo_url style="max-width: 100px;"
      .media-body
        dl.dl-horizontal
          dt Trogdir UUID
          dd = trogdir_person.uuid
          dt NetID
          dd = trogdir_person.netid
          dt Biola ID
          dd = trogdir_person.biola_id
          dt Email
          dd = mail_to trogdir_person.email, trogdir_person.email

app/views/admin/users/edit.html.slim
.page-segment
  .container
    = form_for @user, url: admin_user_path(@user) do |f|
      .row
        .col-md-12
          h2 Edit #{@user.name}
      .row
        .col-md-6
          .form-group
            = f.label :first_name
            = f.text_field :first_name, class: 'form-control', tabindex: 2

          .form-group
            = f.label :last_name
            = f.text_field :last_name, class: 'form-control', tabindex: 3

          .form-group
            = f.label :username
            #username_warning.alert.alert-warning style="display: none;"
              i.fa.fa-warning>
              | Changing an account's username may cause orphaned data in other Biola applications
            = f.email_field :username, class: 'form-control', data: {warning: '#username_warning'}, tabindex: 4

          .form-group
            = f.label :email
            = f.email_field :email, class: 'form-control', tabindex: 5

          .form-group
            = f.label :password do
              ' Password
              small.text-muted twice
            .row
              .col-sm-6
                = f.password_field :password, class: 'form-control', tabindex: 6
              .col-sm-6
                = f.password_field :password_confirmation, class: 'form-control', tabindex: 7

            .progress style="margin-top: 10px;"
              .progress-bar role="progressbar" style="width: 0%;"
                | very weak

          .form-group
            = f.hidden_field :confirmed_at, value: nil
            => f.check_box :confirmed_at, {tabindex: 8}, f.object.confirmed_at.presence || DateTime.now, nil
            = f.label :confirmed_at, 'Email confirmed'


        .col-md-6
          h3 Associated Biolan
          - if @user.trogdir_uuid?
            = f.hidden_field :trogdir_uuid, value: '', id: 'trogdir_uuid', disabled: true
            = render 'trogdir_person', trogdir_person: @user.trogdir_person, editable: true
          .form-group#trogdir_uuid_form
            = label_tag :trogdir_id, @user.trogdir_uuid? ? 'Assign a Different Biolan' : 'Assign Biolan'
            = hidden_field_tag :trogdir_id_type, 'uuid', id: 'id_type_field'
            .input-group
              = text_field_tag :trogdir_id, nil, class: 'form-control'
              .input-group-btn
                button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
                 span#id_type_label> Trogdir UUID
                 span.caret
                ul.dropdown-menu.dropdown-menu-right
                  li
                    a href="#" data-slug="uuid" Trogdir UUID
                  li
                    a href="#" data-slug="netid" NetID
                  li
                    a href="#" data-slug="biola_id" Biola ID

      .row
        .col-md-12
          .buttons
            = link_to 'Back', admin_user_path(@user), class: 'btn btn-default', tabindex: 10
            .pull-right
              = f.submit 'Update User', class: 'btn btn-primary', tabindex: 9

app/views/admin/users/index.html.slim
.page-segment
  .container
    .row
      .col-sm-12
        h2 Users

        table.table.table-stripped
          tr
            th Name
            th Username
            th User For
            th Status
          - @users.each do |user|
            tr
              td = link_to user.name, admin_user_path(user)
              td = user.username
              td = time_ago_in_words(user.created_at)
              td
                - if user.active?
                  span.text-success> title="Active" data-toggle="tooltip"
                    = fa_icon 'check'

                - if user.new?
                  span.text-warning> title="New user" data-toggle="tooltip"
                    = fa_icon 'star-o'

                - if user.unconfirmed?
                  span.text-info> title="Email not yet confirmed" data-toggle="tooltip"
                    = fa_icon 'envelope-o'

        = paginate @users

app/views/admin/users/show.html.slim
.page-segment
  .container
    .row
      .col-md-12
        h2 = @user.name

    .row
      .col-md-8
        span.uuid.text-muted UUID: #{@user.uuid}

        dl.dl-horizontal
          dt First name
          dd = @user.first_name

          dt Last name
          dd = @user.last_name

          dt Username
          dd = @user.username

          dt Email
          dd
            => mail_to(@user.email, @user.email)
            - if @user.confirmed?
              span.text-success title="Confirmed" data-toggle="tooltip"
                = fa_icon 'check'
            - else
              span.text-warning title="Unconfirmed" data-toggle="tooltip"
                = fa_icon 'clock-o'

        - if @user.trogdir_uuid?
          h3 Associated Biolan
          = render 'trogdir_person', trogdir_person: @user.trogdir_person

      aside.col-md-4
        dl
          dt
            ' Referrer
            i.fa.fa-question-circle.text-muted title="Recorded on first visit" data-toggle="tooltip"
          dd = link_to truncate(@user.referring_url, length: 50), @user.referring_url, title: @user.referring_url

          dt
            ' User Agent
            i.fa.fa-question-circle.text-muted title="Recorded on account creation" data-toggle="tooltip"
          dd
            code = @user.user_agent

          dt
            ' IP Address
            i.fa.fa-question-circle.text-muted title="Recorded on account creation" data-toggle="tooltip"
          dd
            code = @user.ip_address

          dt Created
          dd = @user.created_at.try(:to_s, :long)

          dt Confirmed
          dd = @user.confirmed_at.try(:to_s, :long) || content_tag(:span, 'Unconfirmed', class: 'text-muted')

          dt Updated
          dd = @user.updated_at.try(:to_s, :long)

    .row
      .col-sm-8
        .buttons
          = link_to 'Back', admin_users_path, class: 'btn btn-default'
          .pull-right
            => link_to 'Edit User', edit_admin_user_path(@user), class: 'btn btn-primary'
            = link_to 'Delete User', admin_user_path(@user), method: :delete, data: {confirm: 'Delete user?'}, class: 'btn btn-danger'