config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, except: [:new, :create]
    resources :deleted_users, only: [:index, :show]

    root to: 'users#index'
  end

  resource :user do
    get :delete, on: :member
  end
  get 'create', to: 'users#new'

  resources :sessions, only: :create
  get '/destroy_session', to: 'sessions#destroy', as: :destroy_session

  get '/confirm/:key', to: 'email_confirmations#confirm', as: :confirm_email
  get '/resend_confirmation', to: 'email_confirmations#resend', as: :resend_confirmation

  resources :forgot_passwords, only: [:new, :create, :edit, :update]

  # this is just a convenience to create a named route to rack-cas' logout
  get '/logout' => -> env { [404, { 'Content-Type' => 'text/html' }, ['Rack::CAS should have caught this']] }, as: :cas_logout

  root to: 'users#new'
end

app/views/layouts/_account_list.html.slim
/ This file will provide the frontend toolkit with a dropdown list
/   if you are authenticated when you click the user icon in the top right.

- if current_user.is_a? NonBiolan
  - content_for :account_list do
    li
      = link_to user_path do
        i.fa.fa-user>
        | Edit Account Info
    li
      = link_to user_path(anchor: 'change_password') do
        i.fa.fa-key>
        | Change Password
    li
      = link_to destroy_session_path do
        i.fa.fa-power-off>
        | Logout
- else
  - content_for :account_list do
    li = link_to cas_logout_path do
      i.fa.fa-power-off>
      | Logout

app/views/layouts/admin.html.slim
doctype html
html lang="en-us"
  head
    title Accounts Admin
    / frontend_toolkit/head includes default html head tags and csrf_meta_tags
    = render 'frontend_toolkit/head', title: 'Accounts'
    = stylesheet_link_tag 'application', media: 'all'

  body class="admin #{controller_name} #{action_name}"
    = render 'layouts/account_list'
    = render 'frontend_toolkit/biola_header', enable_auth: true

    #site_header
      .page-segment.segment-bold style="padding: 10px 0"
        .container
          .row
            .col-sm-6
              h1.site-title
                = link_to "#{Settings.app.name} Admin", admin_root_path
                p.lead Manage non-Biolan user accounts
            .col-sm-6
              -if Admin::UserPolicy.new(current_user, User).index?
                .search_form.form-top-margin
                  .search_input
                    = fa_icon 'search'
                    = form_tag search_path, method: :get do
                      = text_field_tag 'q', params[:q], placeholder: 'Search names, emails, UUIDs...', tabindex: 1
                      = submit_tag 'Search', class: 'hide'
      #menu
        .container
          ul.list-inline
            li = link_to 'Users', admin_users_path, class: ('active' if controller_name == 'users')
            li = link_to 'Deleted Users', admin_deleted_users_path, class: ('active' if controller_name == 'deleted_users')

      .wrapper-site
        - all_messages.each do |message|
          .alert class="alert-#{message.type}"
            button.close type="button" data-dismiss="alert"
              span &times;
            = fa_icon message.icon, text: message.text

        = yield

      = render 'frontend_toolkit/global_marketing_footer'

      = javascript_include_tag 'application'

app/views/layouts/application.html.slim
doctype html
html lang="en-us"
  head
    title Accounts
    / frontend_toolkit/head includes default html head tags and csrf_meta_tags
    = render 'frontend_toolkit/head', title: 'Accounts'
    = stylesheet_link_tag 'application', media: 'all'

  body class="#{controller_name} #{action_name}"
    = render 'layouts/account_list'
    = render 'frontend_toolkit/biola_header', enable_auth: true

    #site_header
      .page-segment.segment-bold style="padding: 10px 0"
        .container
          .row
            .col-sm-6
              h1.site-title
                = link_to Settings.app.name, root_path
                p.lead Manage your Biola University account

      .wrapper-site
        - all_messages.each do |message|
          .alert class="alert-#{message.type}"
            button.close type="button" data-dismiss="alert"
              span &times;
            = fa_icon message.icon, text: message.text

        = yield

      = render 'frontend_toolkit/global_marketing_footer'

      = javascript_include_tag 'application'
      = yield :javascript